// GENERATED FILE — do not edit by hand. Run: npm run countries:generate
// Built from the same cleaned countries-50m topology the globe draws
// (atlasTopo.generated.ts), so every place on the map is loggable.
// 238 places: 200 countries, 38 territories.

import type { CatalogCountry } from "./countries";

// The canonical region taxonomy. CatalogCountry.region is the Region union, so
// a label outside this list is a type error anywhere in the app.
export const REGION_NAMES = [
  "North Africa",
  "Horn of Africa",
  "East Africa",
  "Central Africa",
  "West Africa",
  "Southern Africa",
  "Western Asia",
  "Caucasus",
  "Central Asia",
  "South Asia",
  "East Asia",
  "Southeast Asia",
  "Eastern Europe",
  "Northern Europe",
  "Southern Europe",
  "Western Europe",
  "Central Europe",
  "North America",
  "Central America",
  "Caribbean",
  "South America",
  "Oceania",
  "Antarctica",
  "Indian Ocean",
  "South Atlantic",
] as const;

export type Region = (typeof REGION_NAMES)[number];

export const COUNTRY_CATALOG: CatalogCountry[] = [
  { id: "4", name: "Afghanistan", region: "Central Asia", kind: "country", lon: 65.9, lat: 33.8 },
  { id: "248", name: "Åland Islands", region: "Northern Europe", kind: "territory", parentId: "246", lon: 19.9, lat: 60.2 },
  { id: "8", name: "Albania", region: "Southern Europe", kind: "country", lon: 20.1, lat: 41.1 },
  { id: "12", name: "Algeria", region: "North Africa", kind: "country", lon: 2.6, lat: 28 },
  { id: "16", name: "American Samoa", region: "Oceania", kind: "territory", parentId: "840", lon: -170.7, lat: -14.3 },
  { id: "20", name: "Andorra", region: "Southern Europe", kind: "country", lon: 1.6, lat: 42.5 },
  { id: "24", name: "Angola", region: "Central Africa", kind: "country", lon: 17.6, lat: -12.3 },
  { id: "660", name: "Anguilla", region: "Caribbean", kind: "territory", parentId: "826", lon: -63.1, lat: 18.2 },
  { id: "10", name: "Antarctica", region: "Antarctica", kind: "country", lon: 83, lat: -84.7 },
  { id: "28", name: "Antigua and Barbuda", region: "Caribbean", kind: "country", lon: -61.8, lat: 17.1 },
  { id: "32", name: "Argentina", region: "South America", kind: "country", lon: -64, lat: -34 },
  { id: "51", name: "Armenia", region: "Caucasus", kind: "country", lon: 44.9, lat: 40.3 },
  { id: "533", name: "Aruba", region: "Caribbean", kind: "territory", parentId: "528", lon: -70, lat: 12.5 },
  { id: "36", name: "Australia", region: "Oceania", kind: "country", lon: 134, lat: -25 },
  { id: "40", name: "Austria", region: "Central Europe", kind: "country", lon: 14.3, lat: 47.6 },
  { id: "31", name: "Azerbaijan", region: "Caucasus", kind: "country", lon: 47.7, lat: 40.3 },
  { id: "44", name: "Bahamas", region: "Caribbean", kind: "country", lon: -78, lat: 24.7 },
  { id: "48", name: "Bahrain", region: "Western Asia", kind: "country", lon: 50.5, lat: 26 },
  { id: "50", name: "Bangladesh", region: "South Asia", kind: "country", lon: 90, lat: 24 },
  { id: "52", name: "Barbados", region: "Caribbean", kind: "country", lon: -59.6, lat: 13.2 },
  { id: "112", name: "Belarus", region: "Eastern Europe", kind: "country", lon: 28, lat: 53.5 },
  { id: "56", name: "Belgium", region: "Western Europe", kind: "country", lon: 4.5, lat: 50.6 },
  { id: "84", name: "Belize", region: "Central America", kind: "country", lon: -88.7, lat: 17.2 },
  { id: "204", name: "Benin", region: "West Africa", kind: "country", lon: 2.3, lat: 9.6 },
  { id: "60", name: "Bermuda", region: "North America", kind: "territory", parentId: "826", lon: -64.8, lat: 32.3 },
  { id: "64", name: "Bhutan", region: "South Asia", kind: "country", lon: 90.4, lat: 27.4 },
  { id: "68", name: "Bolivia", region: "South America", kind: "country", lon: -64.7, lat: -16.7 },
  { id: "70", name: "Bosnia and Herzegovina", region: "Southern Europe", kind: "country", lon: 17.8, lat: 44.2 },
  { id: "72", name: "Botswana", region: "Southern Africa", kind: "country", lon: 23.8, lat: -22.2 },
  { id: "76", name: "Brazil", region: "South America", kind: "country", lon: -51, lat: -12 },
  { id: "86", name: "British Indian Ocean Territory", region: "Indian Ocean", kind: "territory", parentId: "826", lon: 72.4, lat: -7.3 },
  { id: "92", name: "British Virgin Islands", region: "Caribbean", kind: "territory", parentId: "826", lon: -64.6, lat: 18.4 },
  { id: "96", name: "Brunei", region: "Southeast Asia", kind: "country", lon: 114.6, lat: 4.5 },
  { id: "100", name: "Bulgaria", region: "Eastern Europe", kind: "country", lon: 25, lat: 42.7 },
  { id: "854", name: "Burkina Faso", region: "West Africa", kind: "country", lon: -1.8, lat: 12.3 },
  { id: "108", name: "Burundi", region: "East Africa", kind: "country", lon: 29.9, lat: -3.4 },
  { id: "132", name: "Cabo Verde", region: "West Africa", kind: "country", lon: -23.6, lat: 15.1 },
  { id: "116", name: "Cambodia", region: "Southeast Asia", kind: "country", lon: 105, lat: 12.5 },
  { id: "120", name: "Cameroon", region: "Central Africa", kind: "country", lon: 12.7, lat: 5.7 },
  { id: "124", name: "Canada", region: "North America", kind: "country", lon: -106, lat: 58 },
  { id: "136", name: "Cayman Islands", region: "Caribbean", kind: "territory", parentId: "826", lon: -81.3, lat: 19.3 },
  { id: "140", name: "Central African Republic", region: "Central Africa", kind: "country", lon: 20.5, lat: 6.6 },
  { id: "148", name: "Chad", region: "Central Africa", kind: "country", lon: 18.6, lat: 15.3 },
  { id: "152", name: "Chile", region: "South America", kind: "country", lon: -71, lat: -30 },
  { id: "156", name: "China", region: "East Asia", kind: "country", lon: 104, lat: 35 },
  { id: "170", name: "Colombia", region: "South America", kind: "country", lon: -73, lat: 4 },
  { id: "174", name: "Comoros", region: "Indian Ocean", kind: "country", lon: 43.3, lat: -11.7 },
  { id: "178", name: "Congo", region: "Central Africa", kind: "country", lon: 15.2, lat: -0.8 },
  { id: "184", name: "Cook Islands", region: "Oceania", kind: "territory", parentId: "554", lon: -159.8, lat: -21.2 },
  { id: "188", name: "Costa Rica", region: "Central America", kind: "country", lon: -84.2, lat: 10 },
  { id: "384", name: "Côte d'Ivoire", region: "West Africa", kind: "country", lon: -5.6, lat: 7.6 },
  { id: "191", name: "Croatia", region: "Southern Europe", kind: "country", lon: 16.4, lat: 45.2 },
  { id: "192", name: "Cuba", region: "Caribbean", kind: "country", lon: -78.9, lat: 21.6 },
  { id: "531", name: "Curaçao", region: "Caribbean", kind: "territory", parentId: "528", lon: -69, lat: 12.2 },
  { id: "196", name: "Cyprus", region: "Western Asia", kind: "country", lon: 33, lat: 34.9 },
  { id: "203", name: "Czechia", region: "Central Europe", kind: "country", lon: 15.5, lat: 49.8 },
  { id: "208", name: "Denmark", region: "Northern Europe", kind: "country", lon: 9.5, lat: 56 },
  { id: "262", name: "Djibouti", region: "Horn of Africa", kind: "country", lon: 42.6, lat: 11.7 },
  { id: "212", name: "Dominica", region: "Caribbean", kind: "country", lon: -61.4, lat: 15.4 },
  { id: "214", name: "Dominican Republic", region: "Caribbean", kind: "country", lon: -70.5, lat: 18.9 },
  { id: "180", name: "DR Congo", region: "Central Africa", kind: "country", lon: 23.6, lat: -2.9 },
  { id: "218", name: "Ecuador", region: "South America", kind: "country", lon: -78, lat: -1.5 },
  { id: "818", name: "Egypt", region: "North Africa", kind: "country", lon: 30, lat: 27 },
  { id: "222", name: "El Salvador", region: "Central America", kind: "country", lon: -88.9, lat: 13.7 },
  { id: "226", name: "Equatorial Guinea", region: "Central Africa", kind: "country", lon: 10.5, lat: 1.6 },
  { id: "232", name: "Eritrea", region: "Horn of Africa", kind: "country", lon: 38.8, lat: 15.4 },
  { id: "233", name: "Estonia", region: "Northern Europe", kind: "country", lon: 25.8, lat: 58.7 },
  { id: "748", name: "Eswatini", region: "Southern Africa", kind: "country", lon: 31.5, lat: -26.6 },
  { id: "231", name: "Ethiopia", region: "Horn of Africa", kind: "country", lon: 39.6, lat: 8.6 },
  { id: "238", name: "Falkland Islands", region: "South America", kind: "territory", parentId: "826", lon: -58.8, lat: -51.7 },
  { id: "234", name: "Faroe Islands", region: "Northern Europe", kind: "territory", parentId: "208", lon: -6.9, lat: 62.2 },
  { id: "242", name: "Fiji", region: "Oceania", kind: "country", lon: 178, lat: -17.8 },
  { id: "246", name: "Finland", region: "Northern Europe", kind: "country", lon: 26, lat: 64 },
  { id: "250", name: "France", region: "Western Europe", kind: "country", lon: 2.3, lat: 46.6 },
  { id: "258", name: "French Polynesia", region: "Oceania", kind: "territory", parentId: "250", lon: -149.4, lat: -17.7 },
  { id: "260", name: "French Southern Lands", region: "Indian Ocean", kind: "territory", parentId: "250", lon: 69.5, lat: -49.3 },
  { id: "266", name: "Gabon", region: "Central Africa", kind: "country", lon: 11.8, lat: -0.6 },
  { id: "270", name: "Gambia", region: "West Africa", kind: "country", lon: -15.4, lat: 13.5 },
  { id: "268", name: "Georgia", region: "Caucasus", kind: "country", lon: 43.5, lat: 42.2 },
  { id: "276", name: "Germany", region: "Western Europe", kind: "country", lon: 10.4, lat: 51.2 },
  { id: "288", name: "Ghana", region: "West Africa", kind: "country", lon: -1.2, lat: 7.9 },
  { id: "300", name: "Greece", region: "Southern Europe", kind: "country", lon: 22, lat: 39.3 },
  { id: "304", name: "Greenland", region: "North America", kind: "territory", parentId: "208", lon: -41.8, lat: 73.1 },
  { id: "308", name: "Grenada", region: "Caribbean", kind: "country", lon: -61.7, lat: 12.1 },
  { id: "316", name: "Guam", region: "Oceania", kind: "territory", parentId: "840", lon: 144.8, lat: 13.4 },
  { id: "320", name: "Guatemala", region: "Central America", kind: "country", lon: -90.4, lat: 15.7 },
  { id: "831", name: "Guernsey", region: "Northern Europe", kind: "territory", parentId: "826", lon: -2.6, lat: 49.5 },
  { id: "324", name: "Guinea", region: "West Africa", kind: "country", lon: -10.9, lat: 10.4 },
  { id: "624", name: "Guinea-Bissau", region: "West Africa", kind: "country", lon: -14.9, lat: 12.1 },
  { id: "328", name: "Guyana", region: "South America", kind: "country", lon: -59, lat: 4.8 },
  { id: "332", name: "Haiti", region: "Caribbean", kind: "country", lon: -72.7, lat: 18.9 },
  { id: "334", name: "Heard and McDonald Islands", region: "Indian Ocean", kind: "territory", parentId: "36", lon: 73.5, lat: -53.1 },
  { id: "340", name: "Honduras", region: "Central America", kind: "country", lon: -86.6, lat: 14.8 },
  { id: "344", name: "Hong Kong", region: "East Asia", kind: "territory", parentId: "156", lon: 114.1, lat: 22.4 },
  { id: "348", name: "Hungary", region: "Central Europe", kind: "country", lon: 19.5, lat: 47.2 },
  { id: "352", name: "Iceland", region: "Northern Europe", kind: "country", lon: -18.6, lat: 65 },
  { id: "356", name: "India", region: "South Asia", kind: "country", lon: 78.9, lat: 22 },
  { id: "360", name: "Indonesia", region: "Southeast Asia", kind: "country", lon: 118, lat: -2 },
  { id: "364", name: "Iran", region: "Western Asia", kind: "country", lon: 53, lat: 32 },
  { id: "368", name: "Iraq", region: "Western Asia", kind: "country", lon: 43.8, lat: 33 },
  { id: "372", name: "Ireland", region: "Northern Europe", kind: "country", lon: -8, lat: 53.2 },
  { id: "833", name: "Isle of Man", region: "Northern Europe", kind: "territory", parentId: "826", lon: -4.5, lat: 54.2 },
  { id: "376", name: "Israel", region: "Western Asia", kind: "country", lon: 35, lat: 31.4 },
  { id: "380", name: "Italy", region: "Southern Europe", kind: "country", lon: 12.6, lat: 42.5 },
  { id: "388", name: "Jamaica", region: "Caribbean", kind: "country", lon: -77.3, lat: 18.2 },
  { id: "392", name: "Japan", region: "East Asia", kind: "country", lon: 138.2, lat: 37.5 },
  { id: "832", name: "Jersey", region: "Northern Europe", kind: "territory", parentId: "826", lon: -2.1, lat: 49.2 },
  { id: "400", name: "Jordan", region: "Western Asia", kind: "country", lon: 36.5, lat: 31 },
  { id: "398", name: "Kazakhstan", region: "Central Asia", kind: "country", lon: 67.2, lat: 48.4 },
  { id: "404", name: "Kenya", region: "East Africa", kind: "country", lon: 38, lat: 0.5 },
  { id: "296", name: "Kiribati", region: "Oceania", kind: "country", lon: -157.4, lat: 1.9 },
  { id: "kosovo", name: "Kosovo", region: "Southern Europe", kind: "country", lon: 20.9, lat: 42.6 },
  { id: "414", name: "Kuwait", region: "Western Asia", kind: "country", lon: 47.6, lat: 29.3 },
  { id: "417", name: "Kyrgyzstan", region: "Central Asia", kind: "country", lon: 74.5, lat: 41.5 },
  { id: "418", name: "Laos", region: "Southeast Asia", kind: "country", lon: 103.8, lat: 18.5 },
  { id: "428", name: "Latvia", region: "Northern Europe", kind: "country", lon: 24.9, lat: 56.9 },
  { id: "422", name: "Lebanon", region: "Western Asia", kind: "country", lon: 35.8, lat: 33.9 },
  { id: "426", name: "Lesotho", region: "Southern Africa", kind: "country", lon: 28.2, lat: -29.6 },
  { id: "430", name: "Liberia", region: "West Africa", kind: "country", lon: -9.3, lat: 6.5 },
  { id: "434", name: "Libya", region: "North Africa", kind: "country", lon: 18.1, lat: 27 },
  { id: "438", name: "Liechtenstein", region: "Central Europe", kind: "country", lon: 9.5, lat: 47.1 },
  { id: "440", name: "Lithuania", region: "Northern Europe", kind: "country", lon: 23.9, lat: 55.3 },
  { id: "442", name: "Luxembourg", region: "Western Europe", kind: "country", lon: 6.1, lat: 49.8 },
  { id: "446", name: "Macau", region: "East Asia", kind: "territory", parentId: "156", lon: 113.5, lat: 22.2 },
  { id: "450", name: "Madagascar", region: "East Africa", kind: "country", lon: 46.7, lat: -19.3 },
  { id: "454", name: "Malawi", region: "East Africa", kind: "country", lon: 34.3, lat: -13.2 },
  { id: "458", name: "Malaysia", region: "Southeast Asia", kind: "country", lon: 102, lat: 4 },
  { id: "462", name: "Maldives", region: "South Asia", kind: "country", lon: 73.5, lat: 4.2 },
  { id: "466", name: "Mali", region: "West Africa", kind: "country", lon: -3.6, lat: 17.3 },
  { id: "470", name: "Malta", region: "Southern Europe", kind: "country", lon: 14.4, lat: 35.9 },
  { id: "584", name: "Marshall Islands", region: "Oceania", kind: "country", lon: 171.2, lat: 7.1 },
  { id: "478", name: "Mauritania", region: "West Africa", kind: "country", lon: -10.4, lat: 20.2 },
  { id: "480", name: "Mauritius", region: "Indian Ocean", kind: "country", lon: 57.6, lat: -20.3 },
  { id: "484", name: "Mexico", region: "North America", kind: "country", lon: -102.5, lat: 23.6 },
  { id: "583", name: "Micronesia", region: "Oceania", kind: "country", lon: 158.2, lat: 6.9 },
  { id: "498", name: "Moldova", region: "Eastern Europe", kind: "country", lon: 28.5, lat: 47.2 },
  { id: "492", name: "Monaco", region: "Western Europe", kind: "country", lon: 7.4, lat: 43.8 },
  { id: "496", name: "Mongolia", region: "East Asia", kind: "country", lon: 103.1, lat: 47 },
  { id: "499", name: "Montenegro", region: "Southern Europe", kind: "country", lon: 19.2, lat: 42.8 },
  { id: "500", name: "Montserrat", region: "Caribbean", kind: "territory", parentId: "826", lon: -62.2, lat: 16.7 },
  { id: "504", name: "Morocco", region: "North Africa", kind: "country", lon: -6.8, lat: 31.8 },
  { id: "508", name: "Mozambique", region: "East Africa", kind: "country", lon: 35.6, lat: -17.2 },
  { id: "104", name: "Myanmar", region: "Southeast Asia", kind: "country", lon: 96.5, lat: 21.1 },
  { id: "516", name: "Namibia", region: "Southern Africa", kind: "country", lon: 17.2, lat: -22.1 },
  { id: "520", name: "Nauru", region: "Oceania", kind: "country", lon: 166.9, lat: -0.5 },
  { id: "524", name: "Nepal", region: "South Asia", kind: "country", lon: 84, lat: 28 },
  { id: "528", name: "Netherlands", region: "Western Europe", kind: "country", lon: 5.3, lat: 52.1 },
  { id: "540", name: "New Caledonia", region: "Oceania", kind: "territory", parentId: "250", lon: 165.5, lat: -21.3 },
  { id: "554", name: "New Zealand", region: "Oceania", kind: "country", lon: 172, lat: -41 },
  { id: "558", name: "Nicaragua", region: "Central America", kind: "country", lon: -85, lat: 12.8 },
  { id: "562", name: "Niger", region: "West Africa", kind: "country", lon: 9.3, lat: 17.4 },
  { id: "566", name: "Nigeria", region: "West Africa", kind: "country", lon: 8, lat: 9 },
  { id: "570", name: "Niue", region: "Oceania", kind: "territory", parentId: "554", lon: -169.9, lat: -19 },
  { id: "574", name: "Norfolk Island", region: "Oceania", kind: "territory", parentId: "36", lon: 167.9, lat: -29.1 },
  { id: "408", name: "North Korea", region: "East Asia", kind: "country", lon: 127.2, lat: 40.1 },
  { id: "807", name: "North Macedonia", region: "Southern Europe", kind: "country", lon: 21.7, lat: 41.6 },
  { id: "n-cyprus", name: "Northern Cyprus", region: "Western Asia", kind: "country", lon: 33.6, lat: 35.3 },
  { id: "580", name: "Northern Mariana Islands", region: "Oceania", kind: "territory", parentId: "840", lon: 145.7, lat: 15.2 },
  { id: "578", name: "Norway", region: "Northern Europe", kind: "country", lon: 9, lat: 61 },
  { id: "512", name: "Oman", region: "Western Asia", kind: "country", lon: 56.1, lat: 20.6 },
  { id: "586", name: "Pakistan", region: "South Asia", kind: "country", lon: 70, lat: 30 },
  { id: "585", name: "Palau", region: "Oceania", kind: "country", lon: 134.6, lat: 7.5 },
  { id: "275", name: "Palestine", region: "Western Asia", kind: "country", lon: 35.2, lat: 31.9 },
  { id: "591", name: "Panama", region: "Central America", kind: "country", lon: -80.1, lat: 8.5 },
  { id: "598", name: "Papua New Guinea", region: "Oceania", kind: "country", lon: 144.2, lat: -6.6 },
  { id: "600", name: "Paraguay", region: "South America", kind: "country", lon: -58.4, lat: -23.2 },
  { id: "604", name: "Peru", region: "South America", kind: "country", lon: -75, lat: -9.5 },
  { id: "608", name: "Philippines", region: "Southeast Asia", kind: "country", lon: 122, lat: 13 },
  { id: "612", name: "Pitcairn Islands", region: "Oceania", kind: "territory", parentId: "826", lon: -128.3, lat: -24.4 },
  { id: "616", name: "Poland", region: "Central Europe", kind: "country", lon: 19, lat: 52 },
  { id: "620", name: "Portugal", region: "Southern Europe", kind: "country", lon: -8, lat: 39.5 },
  { id: "630", name: "Puerto Rico", region: "Caribbean", kind: "territory", parentId: "840", lon: -66.5, lat: 18.2 },
  { id: "634", name: "Qatar", region: "Western Asia", kind: "country", lon: 51.2, lat: 25.3 },
  { id: "642", name: "Romania", region: "Eastern Europe", kind: "country", lon: 25, lat: 45.9 },
  { id: "643", name: "Russia", region: "Eastern Europe", kind: "country", lon: 100, lat: 61 },
  { id: "646", name: "Rwanda", region: "East Africa", kind: "country", lon: 29.9, lat: -2 },
  { id: "654", name: "Saint Helena", region: "South Atlantic", kind: "territory", parentId: "826", lon: -5.7, lat: -16 },
  { id: "659", name: "Saint Kitts and Nevis", region: "Caribbean", kind: "country", lon: -62.7, lat: 17.3 },
  { id: "662", name: "Saint Lucia", region: "Caribbean", kind: "country", lon: -61, lat: 13.9 },
  { id: "666", name: "Saint Pierre and Miquelon", region: "North America", kind: "territory", parentId: "250", lon: -56.3, lat: 46.9 },
  { id: "670", name: "Saint Vincent and the Grenadines", region: "Caribbean", kind: "country", lon: -61.2, lat: 13.3 },
  { id: "652", name: "Saint-Barthélemy", region: "Caribbean", kind: "territory", parentId: "250", lon: -62.8, lat: 17.9 },
  { id: "663", name: "Saint-Martin", region: "Caribbean", kind: "territory", parentId: "250", lon: -63.1, lat: 18.1 },
  { id: "882", name: "Samoa", region: "Oceania", kind: "country", lon: -172.4, lat: -13.6 },
  { id: "674", name: "San Marino", region: "Southern Europe", kind: "country", lon: 12.5, lat: 43.9 },
  { id: "678", name: "São Tomé and Príncipe", region: "Central Africa", kind: "country", lon: 6.6, lat: 0.2 },
  { id: "682", name: "Saudi Arabia", region: "Western Asia", kind: "country", lon: 45, lat: 24 },
  { id: "686", name: "Senegal", region: "West Africa", kind: "country", lon: -14.5, lat: 14.4 },
  { id: "688", name: "Serbia", region: "Southern Europe", kind: "country", lon: 20.8, lat: 44.2 },
  { id: "690", name: "Seychelles", region: "Indian Ocean", kind: "country", lon: 55.5, lat: -4.7 },
  { id: "694", name: "Sierra Leone", region: "West Africa", kind: "country", lon: -11.8, lat: 8.6 },
  { id: "702", name: "Singapore", region: "Southeast Asia", kind: "country", lon: 103.8, lat: 1.4 },
  { id: "534", name: "Sint Maarten", region: "Caribbean", kind: "territory", parentId: "528", lon: -63.1, lat: 18.1 },
  { id: "703", name: "Slovakia", region: "Central Europe", kind: "country", lon: 19.5, lat: 48.7 },
  { id: "705", name: "Slovenia", region: "Central Europe", kind: "country", lon: 14.8, lat: 46.1 },
  { id: "90", name: "Solomon Islands", region: "Oceania", kind: "country", lon: 160.2, lat: -9.6 },
  { id: "706", name: "Somalia", region: "Horn of Africa", kind: "country", lon: 45.7, lat: 4.7 },
  { id: "somaliland", name: "Somaliland", region: "Horn of Africa", kind: "country", lon: 46.3, lat: 9.7 },
  { id: "710", name: "South Africa", region: "Southern Africa", kind: "country", lon: 24, lat: -29 },
  { id: "239", name: "South Georgia & the Sandwich Islands", region: "South Atlantic", kind: "territory", parentId: "826", lon: -36.7, lat: -54.4 },
  { id: "410", name: "South Korea", region: "East Asia", kind: "country", lon: 127.8, lat: 36.5 },
  { id: "728", name: "South Sudan", region: "East Africa", kind: "country", lon: 30.3, lat: 7.3 },
  { id: "724", name: "Spain", region: "Southern Europe", kind: "country", lon: -3.7, lat: 40.2 },
  { id: "144", name: "Sri Lanka", region: "South Asia", kind: "country", lon: 80.7, lat: 7.9 },
  { id: "729", name: "Sudan", region: "North Africa", kind: "country", lon: 29.9, lat: 16 },
  { id: "740", name: "Suriname", region: "South America", kind: "country", lon: -55.9, lat: 4.1 },
  { id: "752", name: "Sweden", region: "Northern Europe", kind: "country", lon: 15, lat: 62 },
  { id: "756", name: "Switzerland", region: "Central Europe", kind: "country", lon: 8.2, lat: 46.8 },
  { id: "760", name: "Syria", region: "Western Asia", kind: "country", lon: 38.5, lat: 35 },
  { id: "158", name: "Taiwan", region: "East Asia", kind: "country", lon: 121, lat: 23.8 },
  { id: "762", name: "Tajikistan", region: "Central Asia", kind: "country", lon: 71, lat: 38.5 },
  { id: "834", name: "Tanzania", region: "East Africa", kind: "country", lon: 34.8, lat: -6.3 },
  { id: "764", name: "Thailand", region: "Southeast Asia", kind: "country", lon: 101, lat: 15 },
  { id: "626", name: "Timor-Leste", region: "Southeast Asia", kind: "country", lon: 125.9, lat: -8.8 },
  { id: "768", name: "Togo", region: "West Africa", kind: "country", lon: 1, lat: 8.5 },
  { id: "776", name: "Tonga", region: "Oceania", kind: "country", lon: -175.2, lat: -21.2 },
  { id: "780", name: "Trinidad and Tobago", region: "Caribbean", kind: "country", lon: -61.3, lat: 10.4 },
  { id: "788", name: "Tunisia", region: "North Africa", kind: "country", lon: 9.5, lat: 34 },
  { id: "792", name: "Turkey", region: "Western Asia", kind: "country", lon: 35, lat: 39 },
  { id: "795", name: "Turkmenistan", region: "Central Asia", kind: "country", lon: 59.4, lat: 39.1 },
  { id: "796", name: "Turks and Caicos Islands", region: "Caribbean", kind: "territory", parentId: "826", lon: -71.7, lat: 21.8 },
  { id: "850", name: "U.S. Virgin Islands", region: "Caribbean", kind: "territory", parentId: "840", lon: -64.8, lat: 17.7 },
  { id: "800", name: "Uganda", region: "East Africa", kind: "country", lon: 32.4, lat: 1.3 },
  { id: "804", name: "Ukraine", region: "Eastern Europe", kind: "country", lon: 31, lat: 49 },
  { id: "784", name: "United Arab Emirates", region: "Western Asia", kind: "country", lon: 54.3, lat: 23.9 },
  { id: "826", name: "United Kingdom", region: "Northern Europe", kind: "country", lon: -1.8, lat: 53 },
  { id: "840", name: "United States", region: "North America", kind: "country", lon: -98, lat: 39.5 },
  { id: "858", name: "Uruguay", region: "South America", kind: "country", lon: -56, lat: -33 },
  { id: "860", name: "Uzbekistan", region: "Central Asia", kind: "country", lon: 63.3, lat: 41.8 },
  { id: "548", name: "Vanuatu", region: "Oceania", kind: "country", lon: 166.8, lat: -15.2 },
  { id: "336", name: "Vatican City", region: "Southern Europe", kind: "country", lon: 12.4, lat: 41.9 },
  { id: "862", name: "Venezuela", region: "South America", kind: "country", lon: -66, lat: 8 },
  { id: "704", name: "Vietnam", region: "Southeast Asia", kind: "country", lon: 106, lat: 16 },
  { id: "876", name: "Wallis and Futuna", region: "Oceania", kind: "territory", parentId: "250", lon: -178.1, lat: -14.3 },
  { id: "732", name: "Western Sahara", region: "North Africa", kind: "country", lon: -12.3, lat: 24.2 },
  { id: "887", name: "Yemen", region: "Western Asia", kind: "country", lon: 47.5, lat: 15.9 },
  { id: "894", name: "Zambia", region: "Southern Africa", kind: "country", lon: 27.8, lat: -13.5 },
  { id: "716", name: "Zimbabwe", region: "Southern Africa", kind: "country", lon: 29.9, lat: -19 },
];
