// GENERATED FILE — do not edit by hand. Run: npm run countries:generate
// Built from world-atlas/countries-110m.json (the dataset the globe draws), so
// every country on the map is loggable. 177 countries.

import type { CatalogCountry } from "./countries";

// The canonical region taxonomy. CatalogCountry.region is the Region union, so
// a label outside this list is a type error anywhere in the app.
export const REGION_NAMES = [
  "North Africa",
  "Horn of Africa",
  "East Africa",
  "Central Africa",
  "West Africa",
  "Southern Africa",
  "Western Asia",
  "Caucasus",
  "Central Asia",
  "South Asia",
  "East Asia",
  "Southeast Asia",
  "Eastern Europe",
  "Northern Europe",
  "Southern Europe",
  "Western Europe",
  "Central Europe",
  "North America",
  "Central America",
  "Caribbean",
  "South America",
  "Oceania",
  "Antarctica",
  "Indian Ocean",
] as const;

export type Region = (typeof REGION_NAMES)[number];

export const COUNTRY_CATALOG: CatalogCountry[] = [
  { id: "4", name: "Afghanistan", region: "Central Asia", lon: 66, lat: 33.8 },
  { id: "8", name: "Albania", region: "Southern Europe", lon: 20, lat: 41.1 },
  { id: "12", name: "Algeria", region: "North Africa", lon: 2.6, lat: 28 },
  { id: "24", name: "Angola", region: "Central Africa", lon: 17.5, lat: -12.3 },
  { id: "10", name: "Antarctica", region: "Antarctica", lon: 83.1, lat: -84.8 },
  { id: "32", name: "Argentina", region: "South America", lon: -64, lat: -34 },
  { id: "51", name: "Armenia", region: "Caucasus", lon: 45, lat: 40.2 },
  { id: "36", name: "Australia", region: "Oceania", lon: 134, lat: -25 },
  { id: "40", name: "Austria", region: "Central Europe", lon: 14.3, lat: 47.6 },
  { id: "31", name: "Azerbaijan", region: "Caucasus", lon: 47.7, lat: 40.3 },
  { id: "44", name: "Bahamas", region: "Caribbean", lon: -77.9, lat: 24.5 },
  { id: "50", name: "Bangladesh", region: "South Asia", lon: 90, lat: 24 },
  { id: "112", name: "Belarus", region: "Eastern Europe", lon: 28, lat: 53.5 },
  { id: "56", name: "Belgium", region: "Western Europe", lon: 4.5, lat: 50.6 },
  { id: "84", name: "Belize", region: "Central America", lon: -88.7, lat: 17.2 },
  { id: "204", name: "Benin", region: "West Africa", lon: 2.3, lat: 9.6 },
  { id: "64", name: "Bhutan", region: "South Asia", lon: 90.5, lat: 27.4 },
  { id: "68", name: "Bolivia", region: "South America", lon: -64.7, lat: -16.7 },
  { id: "70", name: "Bosnia and Herzegovina", region: "Southern Europe", lon: 17.8, lat: 44.2 },
  { id: "72", name: "Botswana", region: "Southern Africa", lon: 23.8, lat: -22.1 },
  { id: "76", name: "Brazil", region: "South America", lon: -51, lat: -12 },
  { id: "96", name: "Brunei", region: "Southeast Asia", lon: 114.9, lat: 4.7 },
  { id: "100", name: "Bulgaria", region: "Eastern Europe", lon: 25, lat: 42.7 },
  { id: "854", name: "Burkina Faso", region: "West Africa", lon: -1.8, lat: 12.3 },
  { id: "108", name: "Burundi", region: "East Africa", lon: 29.9, lat: -3.4 },
  { id: "116", name: "Cambodia", region: "Southeast Asia", lon: 105, lat: 12.5 },
  { id: "120", name: "Cameroon", region: "Central Africa", lon: 12.6, lat: 5.7 },
  { id: "124", name: "Canada", region: "North America", lon: -106, lat: 58 },
  { id: "140", name: "Central African Republic", region: "Central Africa", lon: 20.4, lat: 6.5 },
  { id: "148", name: "Chad", region: "Central Africa", lon: 18.6, lat: 15.3 },
  { id: "152", name: "Chile", region: "South America", lon: -71, lat: -30 },
  { id: "156", name: "China", region: "East Asia", lon: 104, lat: 35 },
  { id: "170", name: "Colombia", region: "South America", lon: -73, lat: 4 },
  { id: "178", name: "Congo", region: "Central Africa", lon: 15.1, lat: -0.8 },
  { id: "188", name: "Costa Rica", region: "Central America", lon: -84.2, lat: 10 },
  { id: "384", name: "Côte d'Ivoire", region: "West Africa", lon: -5.6, lat: 7.6 },
  { id: "191", name: "Croatia", region: "Southern Europe", lon: 16.4, lat: 45.2 },
  { id: "192", name: "Cuba", region: "Caribbean", lon: -78.9, lat: 21.6 },
  { id: "196", name: "Cyprus", region: "Western Asia", lon: 33, lat: 34.9 },
  { id: "203", name: "Czechia", region: "Central Europe", lon: 15.5, lat: 49.8 },
  { id: "208", name: "Denmark", region: "Northern Europe", lon: 9.5, lat: 56 },
  { id: "262", name: "Djibouti", region: "Horn of Africa", lon: 42.5, lat: 11.8 },
  { id: "214", name: "Dominican Republic", region: "Caribbean", lon: -70.5, lat: 18.9 },
  { id: "180", name: "DR Congo", region: "Central Africa", lon: 23.6, lat: -2.8 },
  { id: "218", name: "Ecuador", region: "South America", lon: -78, lat: -1.5 },
  { id: "818", name: "Egypt", region: "North Africa", lon: 30, lat: 27 },
  { id: "222", name: "El Salvador", region: "Central America", lon: -88.9, lat: 13.7 },
  { id: "226", name: "Equatorial Guinea", region: "Central Africa", lon: 10.4, lat: 1.6 },
  { id: "232", name: "Eritrea", region: "Horn of Africa", lon: 38.7, lat: 15.4 },
  { id: "233", name: "Estonia", region: "Northern Europe", lon: 25.8, lat: 58.6 },
  { id: "748", name: "Eswatini", region: "Southern Africa", lon: 31.4, lat: -26.5 },
  { id: "231", name: "Ethiopia", region: "Horn of Africa", lon: 39.6, lat: 8.6 },
  { id: "238", name: "Falkland Islands", region: "South America", lon: -59.4, lat: -51.7 },
  { id: "242", name: "Fiji", region: "Oceania", lon: 178, lat: -17.8 },
  { id: "246", name: "Finland", region: "Northern Europe", lon: 26, lat: 64 },
  { id: "250", name: "France", region: "Western Europe", lon: 2.3, lat: 46.6 },
  { id: "260", name: "French Southern Lands", region: "Indian Ocean", lon: 69.5, lat: -49.3 },
  { id: "266", name: "Gabon", region: "Central Africa", lon: 11.7, lat: -0.6 },
  { id: "270", name: "Gambia", region: "West Africa", lon: -15.4, lat: 13.5 },
  { id: "268", name: "Georgia", region: "Caucasus", lon: 43.5, lat: 42.2 },
  { id: "276", name: "Germany", region: "Western Europe", lon: 10.4, lat: 51.2 },
  { id: "288", name: "Ghana", region: "West Africa", lon: -1.2, lat: 7.9 },
  { id: "300", name: "Greece", region: "Southern Europe", lon: 22, lat: 39.3 },
  { id: "304", name: "Greenland", region: "North America", lon: -42, lat: 73.2 },
  { id: "320", name: "Guatemala", region: "Central America", lon: -90.4, lat: 15.7 },
  { id: "324", name: "Guinea", region: "West Africa", lon: -11.1, lat: 10.5 },
  { id: "624", name: "Guinea-Bissau", region: "West Africa", lon: -15.1, lat: 12 },
  { id: "328", name: "Guyana", region: "South America", lon: -59, lat: 4.8 },
  { id: "332", name: "Haiti", region: "Caribbean", lon: -72.7, lat: 18.9 },
  { id: "340", name: "Honduras", region: "Central America", lon: -86.6, lat: 14.8 },
  { id: "348", name: "Hungary", region: "Central Europe", lon: 19.5, lat: 47.2 },
  { id: "352", name: "Iceland", region: "Northern Europe", lon: -18.8, lat: 65.1 },
  { id: "356", name: "India", region: "South Asia", lon: 78.9, lat: 22 },
  { id: "360", name: "Indonesia", region: "Southeast Asia", lon: 118, lat: -2 },
  { id: "364", name: "Iran", region: "Western Asia", lon: 53, lat: 32 },
  { id: "368", name: "Iraq", region: "Western Asia", lon: 43.8, lat: 33 },
  { id: "372", name: "Ireland", region: "Northern Europe", lon: -8, lat: 53.2 },
  { id: "376", name: "Israel", region: "Western Asia", lon: 35, lat: 31.4 },
  { id: "380", name: "Italy", region: "Southern Europe", lon: 12.6, lat: 42.5 },
  { id: "388", name: "Jamaica", region: "Caribbean", lon: -77.3, lat: 18.1 },
  { id: "392", name: "Japan", region: "East Asia", lon: 138.2, lat: 37.5 },
  { id: "400", name: "Jordan", region: "Western Asia", lon: 36.5, lat: 31 },
  { id: "398", name: "Kazakhstan", region: "Central Asia", lon: 67.2, lat: 48.4 },
  { id: "404", name: "Kenya", region: "East Africa", lon: 38, lat: 0.5 },
  { id: "kosovo", name: "Kosovo", region: "Southern Europe", lon: 20.9, lat: 42.6 },
  { id: "414", name: "Kuwait", region: "Western Asia", lon: 47.6, lat: 29.3 },
  { id: "417", name: "Kyrgyzstan", region: "Central Asia", lon: 74.6, lat: 41.5 },
  { id: "418", name: "Laos", region: "Southeast Asia", lon: 103.8, lat: 18.4 },
  { id: "428", name: "Latvia", region: "Northern Europe", lon: 24.8, lat: 56.8 },
  { id: "422", name: "Lebanon", region: "Western Asia", lon: 35.8, lat: 33.9 },
  { id: "426", name: "Lesotho", region: "Southern Africa", lon: 28.2, lat: -29.6 },
  { id: "430", name: "Liberia", region: "West Africa", lon: -9.4, lat: 6.4 },
  { id: "434", name: "Libya", region: "North Africa", lon: 18, lat: 27 },
  { id: "440", name: "Lithuania", region: "Northern Europe", lon: 23.9, lat: 55.3 },
  { id: "442", name: "Luxembourg", region: "Western Europe", lon: 6, lat: 49.8 },
  { id: "450", name: "Madagascar", region: "East Africa", lon: 46.7, lat: -19.3 },
  { id: "454", name: "Malawi", region: "East Africa", lon: 34.2, lat: -13.2 },
  { id: "458", name: "Malaysia", region: "Southeast Asia", lon: 102, lat: 4 },
  { id: "466", name: "Mali", region: "West Africa", lon: -3.6, lat: 17.2 },
  { id: "478", name: "Mauritania", region: "West Africa", lon: -10.3, lat: 20.2 },
  { id: "484", name: "Mexico", region: "North America", lon: -102.5, lat: 23.6 },
  { id: "498", name: "Moldova", region: "Eastern Europe", lon: 28.4, lat: 47.2 },
  { id: "496", name: "Mongolia", region: "East Asia", lon: 103, lat: 47 },
  { id: "499", name: "Montenegro", region: "Southern Europe", lon: 19.3, lat: 42.8 },
  { id: "504", name: "Morocco", region: "North Africa", lon: -6.8, lat: 31.8 },
  { id: "508", name: "Mozambique", region: "East Africa", lon: 35.5, lat: -17.2 },
  { id: "104", name: "Myanmar", region: "Southeast Asia", lon: 96.5, lat: 20.9 },
  { id: "516", name: "Namibia", region: "Southern Africa", lon: 17.1, lat: -22 },
  { id: "524", name: "Nepal", region: "South Asia", lon: 84, lat: 28 },
  { id: "528", name: "Netherlands", region: "Western Europe", lon: 5.3, lat: 52.1 },
  { id: "540", name: "New Caledonia", region: "Oceania", lon: 165.5, lat: -21.3 },
  { id: "554", name: "New Zealand", region: "Oceania", lon: 172, lat: -41 },
  { id: "558", name: "Nicaragua", region: "Central America", lon: -85, lat: 12.8 },
  { id: "562", name: "Niger", region: "West Africa", lon: 9.3, lat: 17.3 },
  { id: "566", name: "Nigeria", region: "West Africa", lon: 8, lat: 9 },
  { id: "408", name: "North Korea", region: "East Asia", lon: 127.1, lat: 40.1 },
  { id: "807", name: "North Macedonia", region: "Southern Europe", lon: 21.7, lat: 41.6 },
  { id: "n-cyprus", name: "Northern Cyprus", region: "Western Asia", lon: 33.6, lat: 35.3 },
  { id: "578", name: "Norway", region: "Northern Europe", lon: 9, lat: 61 },
  { id: "512", name: "Oman", region: "Western Asia", lon: 56.1, lat: 20.6 },
  { id: "586", name: "Pakistan", region: "South Asia", lon: 70, lat: 30 },
  { id: "275", name: "Palestine", region: "Western Asia", lon: 35.3, lat: 31.9 },
  { id: "591", name: "Panama", region: "Central America", lon: -80.1, lat: 8.5 },
  { id: "598", name: "Papua New Guinea", region: "Oceania", lon: 144.3, lat: -6.6 },
  { id: "600", name: "Paraguay", region: "South America", lon: -58.4, lat: -23.2 },
  { id: "604", name: "Peru", region: "South America", lon: -75, lat: -9.5 },
  { id: "608", name: "Philippines", region: "Southeast Asia", lon: 122, lat: 13 },
  { id: "616", name: "Poland", region: "Central Europe", lon: 19, lat: 52 },
  { id: "620", name: "Portugal", region: "Southern Europe", lon: -8, lat: 39.5 },
  { id: "630", name: "Puerto Rico", region: "Caribbean", lon: -66.5, lat: 18.2 },
  { id: "634", name: "Qatar", region: "Western Asia", lon: 51.2, lat: 25.3 },
  { id: "642", name: "Romania", region: "Eastern Europe", lon: 25, lat: 45.9 },
  { id: "643", name: "Russia", region: "Eastern Europe", lon: 100, lat: 61 },
  { id: "646", name: "Rwanda", region: "East Africa", lon: 29.9, lat: -2 },
  { id: "682", name: "Saudi Arabia", region: "Western Asia", lon: 45, lat: 24 },
  { id: "686", name: "Senegal", region: "West Africa", lon: -14.5, lat: 14.4 },
  { id: "688", name: "Serbia", region: "Southern Europe", lon: 20.8, lat: 44.2 },
  { id: "694", name: "Sierra Leone", region: "West Africa", lon: -11.8, lat: 8.5 },
  { id: "703", name: "Slovakia", region: "Central Europe", lon: 19.5, lat: 48.7 },
  { id: "705", name: "Slovenia", region: "Central Europe", lon: 14.9, lat: 46.1 },
  { id: "90", name: "Solomon Islands", region: "Oceania", lon: 159.1, lat: -7.9 },
  { id: "706", name: "Somalia", region: "Horn of Africa", lon: 45.7, lat: 4.7 },
  { id: "somaliland", name: "Somaliland", region: "Horn of Africa", lon: 46.2, lat: 9.8 },
  { id: "710", name: "South Africa", region: "Southern Africa", lon: 24, lat: -29 },
  { id: "410", name: "South Korea", region: "East Asia", lon: 127.8, lat: 36.5 },
  { id: "728", name: "South Sudan", region: "East Africa", lon: 30.2, lat: 7.3 },
  { id: "724", name: "Spain", region: "Southern Europe", lon: -3.7, lat: 40.2 },
  { id: "144", name: "Sri Lanka", region: "South Asia", lon: 80.7, lat: 7.9 },
  { id: "729", name: "Sudan", region: "North Africa", lon: 29.8, lat: 16 },
  { id: "740", name: "Suriname", region: "South America", lon: -55.9, lat: 4.1 },
  { id: "752", name: "Sweden", region: "Northern Europe", lon: 15, lat: 62 },
  { id: "756", name: "Switzerland", region: "Central Europe", lon: 8.2, lat: 46.8 },
  { id: "760", name: "Syria", region: "Western Asia", lon: 38.5, lat: 35 },
  { id: "158", name: "Taiwan", region: "East Asia", lon: 121, lat: 23.8 },
  { id: "762", name: "Tajikistan", region: "Central Asia", lon: 71, lat: 38.6 },
  { id: "834", name: "Tanzania", region: "East Africa", lon: 34.7, lat: -6.3 },
  { id: "764", name: "Thailand", region: "Southeast Asia", lon: 101, lat: 15 },
  { id: "626", name: "Timor-Leste", region: "Southeast Asia", lon: 126, lat: -8.8 },
  { id: "768", name: "Togo", region: "West Africa", lon: 1, lat: 8.4 },
  { id: "780", name: "Trinidad and Tobago", region: "Caribbean", lon: -61.3, lat: 10.4 },
  { id: "788", name: "Tunisia", region: "North Africa", lon: 9.5, lat: 34 },
  { id: "792", name: "Turkey", region: "Western Asia", lon: 35, lat: 39 },
  { id: "795", name: "Turkmenistan", region: "Central Asia", lon: 59.3, lat: 39.1 },
  { id: "800", name: "Uganda", region: "East Africa", lon: 32.4, lat: 1.3 },
  { id: "804", name: "Ukraine", region: "Eastern Europe", lon: 31, lat: 49 },
  { id: "784", name: "United Arab Emirates", region: "Western Asia", lon: 54.2, lat: 23.9 },
  { id: "826", name: "United Kingdom", region: "Northern Europe", lon: -1.8, lat: 53 },
  { id: "840", name: "United States", region: "North America", lon: -98, lat: 39.5 },
  { id: "858", name: "Uruguay", region: "South America", lon: -56, lat: -33 },
  { id: "860", name: "Uzbekistan", region: "Central Asia", lon: 63.4, lat: 41.8 },
  { id: "548", name: "Vanuatu", region: "Oceania", lon: 166.9, lat: -15.2 },
  { id: "862", name: "Venezuela", region: "South America", lon: -66, lat: 8 },
  { id: "704", name: "Vietnam", region: "Southeast Asia", lon: 106, lat: 16 },
  { id: "732", name: "Western Sahara", region: "North Africa", lon: -12.2, lat: 24.3 },
  { id: "887", name: "Yemen", region: "Western Asia", lon: 47.5, lat: 15.9 },
  { id: "894", name: "Zambia", region: "Southern Africa", lon: 27.8, lat: -13.4 },
  { id: "716", name: "Zimbabwe", region: "Southern Africa", lon: 29.8, lat: -18.9 },
];
